# 1.2 Added Direct Statement Link support
# 1.3 Added rss_internal support
# 1.4 Adding functionality to post to Google group
# 2 Added Thoughts and Hints functionality
# 3 ADded functionality to display Interesting Posts from the email group

#application: prashnayantra
#version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: AsanaAssignments.application
  
inbound_services:
- mail  
  